### ISSUE TITLE
Issue from GitLab by John

### ISSUE THREAD

**Issue by hackerncoder** [hackerncoder/Toolbar-Container-Coloring#1]
I don't know if it's possible but would be nice to have an option to hide the line under the tab title.
Another nice option would be to be able to hide the container name and icon from the URL Bar.

**Comment by hackerncoder** [comment]
~~Hide line: contextualIdentities.details.color.toolbar~~

**Comment by hackerncoder** [comment]
Hiding the line might be impossible with current api

**Comment by hackerncoder** [comment]
Container name could be " " or null meaning no name, however icon has to be.

In total: Impossible with current API.

**Comment by maverick74** [comment]
Hi,

Sorry for the late reply and thanks for looking into it!!!

It's sad, i believe it would look great if there was a way to implement it.
Maybe in the future... :)
